import {
  Flower2,
  Sparkles,
  TreePine,
  Wind,
  Flame,
  Leaf,
  Mountain,
  Citrus,
  Cookie,
} from "lucide-react";
import type { Fragrance, ScentFamilyInfo } from "@/lib/types";

export const scentFamilies: ScentFamilyInfo[] = [
  {
    name: "Ambar / Oriental",
    icon: Sparkles,
    description: "Aromas cálidos, dulces y especiados. Proviene de ciertas resinas y vainilla.",
    color: "text-amber-500",
  },
  {
    name: "Floral",
    icon: Flower2,
    description: "Evoca aromas a flores. Ya sea una sola flor (soliflore) o a un conjunto de flores (bouquet).",
    color: "text-pink-500",
  },
  {
    name: "Fougere",
    icon: Leaf,
    description: "Sensación de paseo por el bosque. Notas frescas, herbales, amaderadas.",
    color: "text-green-600",
  },
  {
    name: "Cuero",
    icon: Flame,
    description: "Reproducen el aroma del cuero, a menudo con notas de humo, tabaco, abedul.",
    color: "text-orange-700",
  },
  {
    name: "Cítrica",
    icon: Citrus,
    description: "Aromas frescos y energizantes extraídos de frutas cítricas.",
    color: "text-yellow-500",
  },
  {
    name: "Gourmand",
    icon: Cookie,
    description: "Aromas dulces y comestibles, evocando sensaciones de postres.",
    color: "text-amber-800",
  },
  {
    name: "Amaderada",
    icon: TreePine,
    description: "Notas que evocan aromas de madera, como cedro, sándalo, patchuli y vetiver.",
    color: "text-green-800",
  },
  {
    name: "Chipre",
    icon: Mountain,
    description: "Combinación perfecta entre lo fresco (nota verde) y lo intenso (madera).",
    color: "text-teal-600",
  },
];

export const commonNotes: string[] = Array.from(new Set([
  "Aceite de Cedro",
  "Algodón de azúcar",
  "Almendras",
  "Almizcle",
  "Ámbar",
  "Ante",
  "Azafrán",
  "Azucena",
  "Bergamota",
  "Café",
  "Canela",
  "Caramelo",
  "Cardamomo",
  "Cedro",
  "Cereza",
  "Chocolate blanco",
  "Cilantro",
  "Ciruela",
  "Clavo",
  "Coco",
  "Crema chantilly",
  "Cuero",
  "Dulce de Leche",
  "Durazno",
  "Ébano",
  "Especias cálidas",
  "Flor de Azahar",
  "Flor de Loto",
  "Flores Blancas",
  "Frambuesa",
  "Frutos Rojos",
  "Gardenia",
  "Geranio",
  "Haba Tonka",
  "Higo",
  "Incienso",
  "Iris",
  "Jazmín",
  "Jengibre",
  "Lavanda",
  "Limón",
  "Lirio",
  "Madera de akigala",
  "Madera de cedro",
  "Madera de guayaco",
  "Maderas secas",
  "Maderas salinas",
  "Magnolia",
  "Mandarina",
  "Mango",
  "Manzana",
  "Menta",
  "Miel",
  "Mimosa",
  "Musgo",
  "Musgo de roble",
  "Naranja",
  "Naranja Amarga",
  "Nardos",
  "Neroli",
  "Notas marinas",
  "Notas verdes",
  "Nuez moscada",
  "Orquídea",
  "Oud",
  "Pachulí",
  "Papiro",
  "Peonía",
  "Pera",
  "Pimienta",
  "Pimienta negra",
  "Pimienta Rosa",
  "Piña",
  "Piña madura",
  "Praliné",
  "Ron",
  "Rosa absoluta",
  "Rosas",
  "Salvia",
  "Sándalo",
  "Tabaco Bourbon",
  "Tuberosa",
  "Vainilla",
  "Vainilla Absoluta",
  "Vetiver",
  "Violetas",
  "Ylang Ylang"
])).sort();

export const zaraFragrances: Fragrance[] = [
  // MUJER
  {
    id: 1,
    name: "DEEP GARDEN",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Pera"], middle: ["Nardos"], base: ["Haba Tonka"] },
    description: "Un jardín profundo con notas frescas y florales.",
    equivalence: "GOOD GIRL CH",
  },
  {
    id: 2,
    name: "LIGHTLY BLOOM",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Flor de Loto"], middle: ["Peonía"], base: ["Almizcle"] },
    description: "Una explosión floral ligera y fresca.",
    equivalence: "LIGHT BLUE D&G",
  },
  {
    id: 3,
    name: "FIELDS AT NIGHTFALL",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Coco"], middle: ["Jazmín"], base: ["Sándalo"] },
    description: "Elegancia nocturna con toques de coco y jazmín.",
    equivalence: "ZADIG & VOLTAIRE",
  },
  {
    id: 4,
    name: "NUDE BOUQUET",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Cereza"], middle: ["Peonía"], base: ["Vainilla"] },
    description: "Un bouquet delicado y femenino.",
    equivalence: "MISS DIOR BLOOMIG BOUQUET",
  },
  {
    id: 5,
    name: "APPLE JUICE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Manzana"], middle: ["Naranja"], base: ["Pomelo"] },
    description: "Frescura frutal y chispeante.",
    equivalence: "CHANCE EAU TENDRE CHANEL",
  },
  {
    id: 6,
    name: "WONDER ROSE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Frutos Rojos"], middle: ["Durazno"], base: ["Jazmín"] },
    description: "Un aroma frutal cautivador.",
    equivalence: "NARCISO FOR HER",
  },
  {
    id: 7,
    name: "GARDENIA",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Frambuesa"], middle: ["Gardenia"], base: ["Flor de Azahar"] },
    description: "Clásico floral intenso y sofisticado.",
    equivalence: "BLACK OPIUM YSL",
  },
  {
    id: 8,
    name: "ORCHID",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Durazno"], middle: ["Lirio"], base: ["Rosas"] },
    description: "Notas florales con un toque afrutado de durazno.",
    equivalence: "BOMBSHELL VS",
  },
  {
    id: 9,
    name: "HIBISCUS",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Maracuyá"], middle: ["Mango"], base: ["Naranja"] },
    description: "Una fragancia frutal tropical y exótica.",
    equivalence: "LOEWE SOLO",
  },
  {
    id: 10,
    name: "PINK FLAMBÉ",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Orquídea"], middle: ["Jazmín"], base: ["Rosas"] },
    description: "Divertida, femenina y llena de vida.",
    equivalence: "VALENTINO DONNA BORN",
  },
  {
    id: 11,
    name: "PINK FLAMBÉ Summer",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Violetas"], middle: ["Rosas"], base: ["Sándalo"] },
    description: "Versión veraniega y amaderada de Pink Flambé.",
    equivalence: "VIVA LA JUICY COUTURE",
  },
  {
    id: 12,
    name: "GO FRUITY",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Manzana"], middle: ["Durazno"], base: ["Vainilla"] },
    description: "Dulzura frutal irresistible.",
    equivalence: "BURBERRY FOR HER",
  },
  {
    id: 13,
    name: "CHERRY BOMB",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Mandarina"], middle: ["Cereza"], base: ["Rosas"] },
    description: "Una explosión de cereza y flores.",
    equivalence: "TOM FORD LOST CHERRY",
  },
  {
    id: 14,
    name: "RED VAINILLA",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Peonía"], middle: ["Iris"], base: ["Vainilla"] },
    description: "Elegancia floral con una base dulce de vainilla.",
    equivalence: "LA VIE EST BELLE LANCOME",
  },
  {
    id: 15,
    name: "FEMME",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Orquídea"], middle: ["Peonía"], base: ["Sándalo"] },
    description: "Un aroma floral clásico y amaderado.",
    equivalence: "MIRACLE DE LANCOME",
  },
  {
    id: 16,
    name: "FEMME Summer",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Magnolia"], middle: ["Jazmín"], base: ["Mandarina"] },
    description: "Frescura floral y afrutada para el verano.",
    equivalence: "YELLOW DIAMOND, VERSACE",
  },
  {
    id: 17,
    name: "FEMME Winter",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Vainilla"], middle: ["Jazmín"], base: ["Almendras"] },
    description: "Cálida y floral con toques de almendra.",
    equivalence: "AMOR AMOR SUNSHINE",
  },
  {
    id: 18,
    name: "TUBEROSE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Vainilla"], middle: ["Almizcle"], base: ["Sándalo"] },
    description: "Elegancia floral con una base cremosa.",
    equivalence: "J'ADORE EDP DIOR",
  },
  {
    id: 19,
    name: "TUBEROSE Winter",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Nardos"], middle: ["Sándalo"], base: ["Haba Tonka"] },
    description: "Intensa, amaderada y profundamente floral.",
    equivalence: "EUPHORIA CK",
  },
  {
    id: 20,
    name: "ULTRA JUICY",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Limón"], middle: ["Pera"], base: ["Durazno"] },
    description: "Una explosión cítrica y frutal.",
    equivalence: "ESCADA MOON SPARKLE",
  },
  {
    id: 21,
    name: "CASHMERE ROSE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Rosas"], middle: ["Almizcle"], base: ["Durazno"] },
    description: "Suave y delicada como el cashmere.",
    equivalence: "GUCCI FLORA",
  },
  {
    id: 22,
    name: "TWILIGHT MAUVE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Manzana"], middle: ["Bergamota"], base: ["Cedro"] },
    description: "Frescura frutal con un fondo amaderado.",
    equivalence: "BE DELICIOUS DKNY",
  },
  {
    id: 23,
    name: "VIOLET BLOSSOM",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Manzana"], middle: ["Azucena"], base: ["Almendra"] },
    description: "Un aura floral mística y cautivadora.",
    equivalence: "ALIEN MUGLER",
  },
  {
    id: 24,
    name: "SUBLIME EPOQUE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Vainilla"], middle: ["Jazmín"], base: ["Cedro"] },
    description: "Homenaje a la feminidad clásica.",
    equivalence: "MY WAY ARMANI",
  },
  {
    id: 25,
    name: "CHERRY SMOOTHIE",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Cereza"], middle: ["Ciruela"], base: ["Vainilla"] },
    description: "Dulzura frutal intensa y adictiva.",
    equivalence: "BLACK OPIUM OVER RED",
  },
  {
    id: 26,
    name: "MARSHMALLOW ADDICTION",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Caramelo"], middle: ["Coco"], base: ["Vainilla"] },
    description: "Dulzura pura y juguetona.",
    equivalence: "ESCADA ROCKIN RÍO",
  },
  {
    id: 27,
    name: "SULTRY PEAR",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Jazmín"], middle: ["Pera"], base: ["Vainilla"] },
    description: "Sensual combinación de pera y jazmín.",
    equivalence: "LA BELLE JPG",
  },
  {
    id: 28,
    name: "RED TEMPTATION WINTER",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Naranja"], middle: ["Vainilla"], base: ["Cuero"] },
    description: "Elegancia invernal con un toque de cuero.",
    equivalence: "BACCARAT ROUGE 540",
  },
  {
    id: 29,
    name: "RED TEMPTATION ELIXIR",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Azafrán"], middle: ["Naranja"], base: ["Jazmín"] },
    description: "La máxima expresión de la tentación roja.",
    equivalence: "BACCARAT ROUGE 540 EXTRAIT",
  },
  {
    id: 30,
    name: "RED TEMPTATION & SANDALWOOD EXTRACTO",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Azafrán"], middle: ["Pimienta"], base: ["Sándalo"] },
    description: "Un extracto amaderado y especiado con gran profundidad.",
    equivalence: "BACCARAT ROUGE EXTRAIT",
  },
  {
    id: 31,
    name: "RED TEMPTATION & VANILLA EXTRACTO",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Naranja Amarga"], middle: ["Haba Tonka"], base: ["Vainilla Absoluta"] },
    description: "Dulzura sofisticada con un toque cítrico amargo.",
    equivalence: "BACCARAT ROUGE EXTRAIT",
  },
  {
    id: 32,
    name: "SUPREME VANILLA",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Vainilla"], middle: ["Cedro"], base: ["Haba Tonka"] },
    description: "Una vainilla amaderada y profunda.",
    equivalence: "KAYALI VAINILLA 28",
  },
  {
    id: 33,
    name: "HPNOTIC VAINILLA",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Jazmín"], middle: ["Vainilla"], base: ["Dulce de Leche"] },
    description: "Aroma floral y cremoso con notas de dulce de leche.",
    equivalence: "HYPNOTIC POISON DIOR",
  },
  {
    id: 34,
    name: "GOLDEN DECADE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Jazmín"], middle: ["Lavanda"], base: ["Mandarina"] },
    description: "Elegancia floral con un toque de lavanda.",
    equivalence: "LIBRE EDP YSL",
  },
  {
    id: 35,
    name: "GOLDEN DECADE WINTER",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Mandarina"], middle: ["Bergamota"], base: ["Lavanda"] },
    description: "Frescura invernal cítrica y aromática.",
    equivalence: "LIBRE INTENSE YSL",
  },
  {
    id: 36,
    name: "GOLDEN DECADE FLOR",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Piña"], middle: ["Vainilla"], base: ["Jazmín"] },
    description: "Combinación floral y afrutada con piña.",
    equivalence: "LIBRE EDP YSL",
  },
  {
    id: 37,
    name: "MEMORABLE AURA",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Mango"], middle: ["Jazmín"], base: ["Vainilla"] },
    description: "Un aura floral tropical y dulce.",
    equivalence: "ALIEN GODDESS MUGLER",
  },
  {
    id: 38,
    name: "ROSE GOURMAND",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Jazmín"], middle: ["Caramelo"], base: ["Vainilla"] },
    description: "Rosas endulzadas con caramelo y vainilla.",
    equivalence: "MANCERA ROSES VANILLE",
  },
  {
    id: 39,
    name: "AMBER FUSION",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Almizcle"], middle: ["Pachulí"], base: ["Ámbar"] },
    description: "Fusión amaderada y floral con ámbar.",
    equivalence: "ERBA PURA XERJOFF",
  },
  {
    id: 40,
    name: "FASHIONABLY LONDON",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Bergamota"], middle: ["Rosa"], base: ["Almizcle"] },
    description: "Aroma floral and sofisticado inspirado en Londres.",
    equivalence: "DELINA PARFUMS DE MARLY",
  },
  {
    id: 41,
    name: "EBONY WOOD",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Pimienta rosa"], middle: ["Clavo"], base: ["Ébano"] },
    description: "Madera de ébano con notas especiadas de pimienta y clavo.",
    equivalence: "WOOD SAGE & SEA SALT JO MALONE",
  },
  {
    id: 42,
    name: "TUBEREUSE NOIR",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Ylang Ylang"], middle: ["Tuberosa"], base: ["Sándalo"] },
    description: "Una tuberosa oscura y sofisticada.",
    equivalence: "GUCCI BLOOM",
  },
  {
    id: 43,
    name: "SALTY OCEAN BOUQUET",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Flor de azahar"], middle: ["Pimienta negra"], base: ["Maderas salinas"] },
    description: "Un aroma floral fresco con toques marinos y especiados.",
  },
  {
    id: 44,
    name: "ROSE PETALS DROPS",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Rosa absoluta"], middle: ["Pimienta rosa"], base: ["Vainilla"] },
    description: "Elegancia floral con un corazón de rosa pura y un fondo dulce.",
  },
  {
    id: 45,
    name: "AMBER & FIG CASHMERE",
    category: "Mujer",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Higo"], middle: ["Ámbar"], base: ["Maderas suaves (cashmere)"] },
    description: "Calidez ambarada combinada con la frescura frutal del higo.",
  },
  {
    id: 46,
    name: "CAVIAR BERGAMOT",
    category: "Mujer",
    scentFamily: "Cítrica",
    notes: { top: ["Bergamota"], middle: ["Limón"], base: ["Jengibre"] },
    description: "Una fragancia cítrica vibrante y energizante.",
  },
  {
    id: 47,
    name: "ENERGETICALLY NEW YORK ELIXIR PARFUM",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Cardamomo"], middle: ["Jazmín"], base: ["Sándalo"] },
    description: "Sofisticación amaderada inspirada en la energía de Nueva York.",
    equivalence: "SANTAL 33 LE LABO",
  },
  {
    id: 48,
    name: "ELEGANTLY TOKIO",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Lirio"], middle: ["Jazmín"], base: ["Madera de akigala"] },
    description: "Elegancia floral amaderada inspirada en el minimalismo de Tokio.",
    equivalence: "WILD BLUEBELL JO MALONE",
  },
  {
    id: 49,
    name: "ENERGETICALLY NEW YORK",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Cardamomo"], middle: ["Jazmín"], base: ["Sándalo"] },
    description: "Captura la energía vibrante de Nueva York con un toque especiado.",
    equivalence: "SANTAL 33 LE LABO",
  },
  {
    id: 50,
    name: "CAPTIVATINGLY PARIS",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Pera"], middle: ["Almizcle"], base: ["Rosas"] },
    description: "Una edición exclusiva floral y afrutada inspirada en París.",
  },
  {
    id: 51,
    name: "BOLDLY SEOUL",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Mimosa"], middle: ["Violetas"], base: ["Almizcle"] },
    description: "Edición exclusiva con una mezcla fresca y floral de Seúl.",
    equivalence: "MIMOSA & CARDAMOM JO MALONE",
  },
  {
    id: 52,
    name: "RED TEMPTATION SWEET",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Vainilla"], middle: ["Haba Tonka"], base: ["Ámbar", "Musgo"] },
    description: "Una versión intensamente dulce y sofisticada de Red Temptation.",
    equivalence: "BACCARAT ROUGE 540",
  },
  {
    id: 53,
    name: "GOLDEN DECADE SWEET",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Flor de azahar"], middle: ["Mandarina"], base: ["Haba tonka", "Praliné"] },
    description: "ADN de lavanda y flores blancas, pero esta versión \"Sweet\" imita a la perfección el lado más dulce, nocturno, cremoso y avainillado de la versión Intense de YSL.",
    equivalence: "LIBRE INTENSE YSL",
  },
  {
    id: 54,
    name: "VETIVER PAMPLEMOUSSE",
    category: "Mujer",
    scentFamily: "Cítrica",
    notes: { top: ["Pomelo"], middle: ["Mandarina"], base: ["Vetiver"] },
    description: "Frescura cítrica aromática, limpia y chispeante.",
    equivalence: "GRAPEFRUIT JO MALONE",
  },
  {
    id: 55,
    name: "MAGNIFICENTLY DUBAI",
    category: "Mujer",
    scentFamily: "Cuero",
    notes: { top: ["Azafrán"], middle: ["Nuez moscada"], base: ["Cuero"] },
    description: "Sofisticación de cuero especiado con estilo nicho.",
    equivalence: "OUD WOOD TOM FORD STYLE",
  },
  {
    id: 56,
    name: "AMALFI SUNRAY",
    category: "Mujer",
    scentFamily: "Cítrica",
    notes: { top: ["Bergamota"], middle: ["Mandarina"], base: ["Azahar"] },
    description: "Evoca el sol del mediterráneo con notas cítricas y florales.",
    equivalence: "BLU MEDITERRANEO ACQUA DI PARMA",
  },
  {
    id: 57,
    name: "FLEUR DE PATCHOULI",
    category: "Mujer",
    scentFamily: "Chipre",
    notes: { top: ["Peonía"], middle: ["Pachulí"], base: ["Madera de guayaco"] },
    description: "Un chipre floral elegante y atemporal.",
    equivalence: "COCO MADEMOISELLE CHANEL",
  },
  {
    id: 58,
    name: "GRACEFULLY MADRID",
    category: "Mujer",
    scentFamily: "Cítrica",
    notes: { top: ["Naranja"], middle: ["Geranio"], base: ["Almizcle"] },
    description: "Frescura aromática con la elegancia de Madrid.",
    equivalence: "AQUA ALLEGORIA GUERLAIN STYLE",
  },
  {
    id: 59,
    name: "CREATIVELY SHANGHAI",
    category: "Mujer",
    scentFamily: "Cítrica",
    notes: { top: ["Mandarina"], middle: ["Cardamomo"], base: ["Cedro"] },
    description: "Inspirada en el té cítrico con un toque especiado.",
  },
  {
    id: 60,
    name: "STUNNINGLY VENICE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Frutos Rojos"], middle: ["Rosa"], base: ["Bergamota"] },
    description: "Estilo fresco y juvenil con un toque de frutos rojos.",
  },
  {
    id: 61,
    name: "WATERLILY TEA DRESS",
    category: "Mujer",
    scentFamily: "Cítrica",
    notes: { top: ["Menta"], middle: ["Bergamota"], base: ["Almizcle"] },
    description: "Cítrica verde, limpia y refrescante.",
    equivalence: "WILD BLUEBELL JO MALONE",
  },
  {
    id: 62,
    name: "FLEUR D'ORANGER",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Neroli"], middle: ["Flor de Naranjo"], base: ["Ylang Ylang"] },
    description: "Floral cítrica luminosa y pura.",
    equivalence: "ORANGE BLOSSOM JO MALONE",
  },
  {
    id: 63,
    name: "BOHEMIAN BLUEBELLS",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Lavanda"], middle: ["Sándalo"], base: ["Almizcle"] },
    description: "Estilo aromático relajante y natural.",
  },
  {
    id: 64,
    name: "LEATHER JARDIN",
    category: "Mujer",
    scentFamily: "Cuero",
    notes: { top: ["Pomelo"], middle: ["Rosa"], base: ["Cuero"] },
    description: "Cuero seco y sofisticado con matices florales.",
    equivalence: "KELLY CALÈCHE HERMÈS",
  },
  {
    id: 65,
    name: "ANCESTRAL PAPYRUS",
    category: "Mujer",
    scentFamily: "Amaderada",
    notes: { top: ["Pomelo"], middle: ["Papiro"], base: ["Sándalo"] },
    description: "Amaderada limpia y minimalista.",
    equivalence: "SANTAL 33 (VERSIÓN SUAVE)",
  },
  {
    id: 66,
    name: "VIRTUALLY JASMINE",
    category: "Mujer",
    scentFamily: "Floral",
    notes: { top: ["Salvia"], middle: ["Jazmín"], base: ["Almizcle"] },
    description: "Estilo floral limpio y aromático.",
  },
  {
    id: 67,
    name: "COCOA & LATTE",
    category: "Mujer",
    scentFamily: "Gourmand",
    notes: { top: ["Crema chantilly"], middle: ["Chocolate blanco"], base: ["Ante"] },
    description: "La crema chantilly abre la composición con una suavidad aterciopelada que se mezcla con la dulzura cremosa del chocolate blanco. El acorde de ante introduce una textura elegante y ligeramente cálida que equilibra el carácter gourmand con una sofisticación envolvente.",
  },
  {
    id: 68,
    name: "RED TEMPTATION",
    category: "Mujer",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Azafrán", "Naranja amarga", "Cilantro"], middle: ["Praliné", "Jazmín"], base: ["Ámbar", "Musgo de roble", "Almizcle"] },
    description: "Elegante, sofisticado y con ese olor característico a azúcar tostado refinado que dura todo el día.",
    equivalence: "BACCARAT ROUGE 540",
  },

  // HOMBRE
  {
    id: 101,
    name: "Vibrant Leather",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Bergamota"], middle: ["Bambú"], base: ["Cuero"] },
    description: "La fragancia más icónica de Zara Hombre.",
    equivalence: "Aventus by Creed",
  },
  {
    id: 102,
    name: "W/END till 3:00 AM",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Piña"], middle: ["Lavanda"], base: ["Cedro"] },
    description: "Frescura amaderada para la noche.",
  },
  {
    id: 103,
    name: "W/END till 8:00 PM",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Mandarina"], middle: ["Pimienta"], base: ["Cuero"] },
    description: "Intensidad oriental y especiada.",
  },
  {
    id: 104,
    name: "Tobacco Collection Infinite",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Pimienta"], middle: ["Tabaco"], base: ["Madera"] },
    description: "Elegancia clásica con notas de tabaco.",
  },
  {
    id: 105,
    name: "Oud Vibrant Leather",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Bergamota"], middle: ["Incienso"], base: ["Oud"] },
    description: "Una versión mística y profunda de Vibrant Leather con notas de Oud.",
    equivalence: "Oud Wood (Tom Ford) / Aventus",
  },
  {
    id: 106,
    name: "Vibrant Leather Bogoss",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Limón"], middle: ["Piña"], base: ["Cedro"] },
    description: "Frescura frutal y amaderada con un toque tropical.",
    equivalence: "Hacivat (Nishane)",
  },
  {
    id: 107,
    name: "For Him (EDP)",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Bergamota"], middle: ["Cardamomo"], base: ["Sándalo"] },
    description: "Elegancia masculina moderna en concentration Eau de Parfum.",
    equivalence: "Dior Homme",
  },
  {
    id: 108,
    name: "For Him Red Edition",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Naranja"], middle: ["Ámbar"], base: ["Evernyl"] },
    description: "Aroma sofisticado con gran estela y fijación.",
    equivalence: "Baccarat Rouge 540 (MFK)",
  },
  {
    id: 109,
    name: "For Him Rush",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Frambuesa"], middle: ["Violeta"], base: ["Amberwood"] },
    description: "Dinamismo y frescura con notas dulces de frambuesa.",
    equivalence: "Invictus Victory (Paco Rabanne)",
  },
  {
    id: 110,
    name: "Zara Man Silver",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Limón"], middle: ["Jazmín"], base: ["Pachulí"] },
    description: "Frescura clásica y versátil para el día a día.",
    equivalence: "Gucci Guilty Pour Homme",
  },
  {
    id: 111,
    name: "Zara Man Gold",
    category: "Hombre",
    scentFamily: "Gourmand",
    notes: { top: ["Limón"], middle: ["Praliné"], base: ["Ébano"] },
    description: "Dulzura masculina intensa y cautivadora.",
    equivalence: "Black XS (Paco Rabanne)",
  },
  {
    id: 112,
    name: "Zara Man Blue Spirit",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Mandarina"], middle: ["Ylang-ylang"], base: ["Ámbar"] },
    description: "Espíritu libre y refrescante con fondo cálido.",
    equivalence: "Invictus (Paco Rabanne)",
  },
  {
    id: 113,
    name: "Zara Man Uomo",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Bergamota"], middle: ["Canela"], base: ["Ámbar"] },
    description: "Calidez y especias para una presencia inolvidable.",
    equivalence: "1 Million (Paco Rabanne)",
  },
  {
    id: 114,
    name: "TOBACCO COLLECTION Rich Warm Addictive",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Ron"], middle: ["Peonía"], base: ["Tabaco Bourbon"] },
    description: "Aroma cálido, dulce y adictivo para climas fríos.",
    equivalence: "Tobacco Vanille (Tom Ford)",
  },
  {
    id: 115,
    name: "TOBACCO COLLECTION Dark Exclusive Intense",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Manzana"], middle: ["Pimienta"], base: ["Haba Tonka"] },
    description: "Intensidad nocturna y elegante.",
    equivalence: "212 VIP Men (Carolina Herrera)",
  },
  {
    id: 116,
    name: "Sand Desert at Sunset",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Incienso"], middle: ["Canela"], base: ["Haba Tonka"] },
    description: "Evoca el atardecer en el desierto con notas especiadas.",
    equivalence: "Angels' Share (By Kilian)",
  },
  {
    id: 117,
    name: "Lisboa",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Limón"], middle: ["Notas marinas"], base: ["Musgo"] },
    description: "Frescura oceánica inspirada en la capital portuguesa.",
    equivalence: "Acqua di Gio (Armani)",
  },
  {
    id: 118,
    name: "Seoul",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Mandarina"], middle: ["Lavanda"], base: ["Ámbar"] },
    description: "Energía urbana y moderna con toque floral aromático.",
    equivalence: "Invictus (Paco Rabanne)",
  },
  {
    id: 119,
    name: "Seoul EDT Winter",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Mandarina"], middle: ["Manzana"], base: ["Flor de Azahar"] },
    description: "Versión veraniega de Seoul con un toque frutal y floral.",
  },
  {
    id: 120,
    name: "Saffron & Orange Flowers",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Azafrán"], middle: ["Naranja", "Bergamota"], base: ["Almizcle"] },
    description: "Mezcla sofisticada de especias y cítricos con un fondo limpio.",
  },
  {
    id: 121,
    name: "Vibrant Leather Extreme",
    category: "Hombre",
    scentFamily: "Cuero",
    notes: { 
      top: ["Bergamota", "Limón", "Mandarina"], 
      middle: ["Cuero negro", "Azafrán"], 
      base: ["Papiro", "Pachulí", "Notas terrosas", "Algodón de azúcar"] 
    },
    description: "Versión dense y oscura de Vibrant Leather original, con un equilibrio entre frescura cítrica y un fondo dulce y terroso.",
  },
  {
    id: 122,
    name: "Bogoss Vibrant Leather Extreme",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { 
      top: ["Piña madura", "Limón", "Bergamota"], 
      middle: ["Especias cálidas"], 
      base: ["Pachulí", "Papiro", "Maderas secas", "Vainilla"] 
    },
    description: "Una versión intensificada y más compleja que ofrece un secado profundo, amaderado y cambiante con matices especiados.",
  },
  {
    id: 123,
    name: "Zara Night Pour Homme II",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { 
      top: ["Bergamota", "Limón"], 
      middle: ["Lavanda", "Notas marinas"], 
      base: ["Ámbar", "Cedro"] 
    },
    description: "Fragancia fresca, acuática y ligeramente dulce, ideal para el uso diario.",
    equivalence: "Invictus (Paco Rabanne)",
  },
  {
    id: 201,
    name: "EBONY WOOD",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Pimienta rosa"], middle: ["Clavo"], base: ["Ébano"] },
    description: "Madera de ébano con notas especiadas de pimienta y clavo.",
    equivalence: "WOOD SAGE & SEA SALT JO MALONE",
  },
  {
    id: 202,
    name: "VETIVER PAMPLEMOUSSE",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Pomelo"], middle: ["Mandarina"], base: ["Vetiver"] },
    description: "Frescura cítrica aromática, limpia y chispeante.",
    equivalence: "GRAPEFRUIT JO MALONE",
  },
  {
    id: 203,
    name: "ENERGETICALLY NEW YORK",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Cardamomo"], middle: ["Jazmín"], base: ["Sándalo"] },
    description: "Captura la energía vibrante de Nueva York con un toque especiado.",
    equivalence: "SANTAL 33 LE LABO",
  },
  {
    id: 204,
    name: "MAGNIFICENTLY DUBAI",
    category: "Hombre",
    scentFamily: "Cuero",
    notes: { top: ["Azafrán"], middle: ["Nuez moscada"], base: ["Cuero"] },
    description: "Sofisticación de cuero especiado con estilo nicho.",
    equivalence: "OUD WOOD TOM FORD STYLE",
  },
  {
    id: 205,
    name: "AMALFI SUNRAY",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Bergamota"], middle: ["Mandarina"], base: ["Azahar"] },
    description: "Evoca el sol del mediterráneo con notas cítricas y florales.",
    equivalence: "BLU MEDITERRANEO ACQUA DI PARMA",
  },
  {
    id: 206,
    name: "FLEUR DE PATCHOULI",
    category: "Hombre",
    scentFamily: "Chipre",
    notes: { top: ["Peonía"], middle: ["Pachulí"], base: ["Madera de guayaco"] },
    description: "Un chipre floral elegante y atemporal.",
    equivalence: "COCO MADEMOISELLE CHANEL",
  },
  {
    id: 207,
    name: "GRACEFULLY MADRID",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Naranja"], middle: ["Geranio"], base: ["Almizcle"] },
    description: "Frescura aromática con la elegancia de Madrid.",
    equivalence: "AQUA ALLEGORIA GUERLAIN STYLE",
  },
  {
    id: 208,
    name: "CREATIVELY SHANGHAI",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Mandarina"], middle: ["Cardamomo"], base: ["Cedro"] },
    description: "Inspirada en el té cítrico con un toque especiado.",
  },
  {
    id: 209,
    name: "FASHIONABLY LONDON",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Bergamota"], middle: ["Rosa"], base: ["Almizcle"] },
    description: "Aroma floral y sofisticado inspirado en Londres.",
    equivalence: "DELINA PARFUMS DE MARLY",
  },
  {
    id: 210,
    name: "ELEGANTLY TOKIO",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Lirio"], middle: ["Jazmín"], base: ["Madera de akigala"] },
    description: "Elegancia floral amaderada inspirada en el minimalismo de Tokio.",
    equivalence: "WILD BLUEBELL JO MALONE",
  },
  {
    id: 211,
    name: "STUNNINGLY VENICE",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Frutos Rojos"], middle: ["Rosa"], base: ["Bergamota"] },
    description: "Estilo fresco y juvenil con un toque de frutos rojos.",
  },
  {
    id: 212,
    name: "BOLDLY SEOUL",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Mimosa"], middle: ["Violetas"], base: ["Almizcle"] },
    description: "Edición exclusiva con una mezcla fresca y floral de Seúl.",
    equivalence: "MIMOSA & CARDAMOM JO MALONE",
  },
  {
    id: 213,
    name: "WATERLILY TEA DRESS",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Menta"], middle: ["Bergamota"], base: ["Almizcle"] },
    description: "Cítrica verde, limpia y refrescante.",
    equivalence: "WILD BLUEBELL JO MALONE",
  },
  {
    id: 214,
    name: "TUBEREUSE NOIR",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Ylang Ylang"], middle: ["Tuberosa"], base: ["Sándalo"] },
    description: "Una tuberosa oscura y sofisticada.",
    equivalence: "GUCCI BLOOM",
  },
  {
    id: 215,
    name: "FLEUR D'ORANGER",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Neroli"], middle: ["Flor de Naranjo"], base: ["Ylang Ylang"] },
    description: "Floral cítrica luminosa y pura.",
    equivalence: "ORANGE BLOSSOM JO MALONE",
  },
  {
    id: 216,
    name: "BOHEMIAN BLUEBELLS",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Lavanda"], middle: ["Sándalo"], base: ["Almizcle"] },
    description: "Estilo aromático relajante y natural.",
  },
  {
    id: 217,
    name: "LEATHER JARDIN",
    category: "Hombre",
    scentFamily: "Cuero",
    notes: { top: ["Pomelo"], middle: ["Rosa"], base: ["Cuero"] },
    description: "Cuero seco y sofisticado con matices florales.",
    equivalence: "KELLY CALÈCHE HERMÈS",
  },
  {
    id: 218,
    name: "ANCESTRAL PAPYRUS",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Pomelo"], middle: ["Papiro"], base: ["Sándalo"] },
    description: "Amaderada limpia y minimalista.",
    equivalence: "SANTAL 33 (VERSIÓN SUAVE)",
  },
  {
    id: 219,
    name: "VIRTUALLY JASMINE",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Salvia"], middle: ["Jazmín"], base: ["Almizcle"] },
    description: "Estilo floral limpio y aromático.",
  },
  {
    id: 220,
    name: "Vibrant Leather Winter",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Bergamota", "Ciruela"], middle: ["Cuero"], base: [] },
    description: "Una versión invernal cálida y sofisticada de Vibrant Leather.",
    equivalence: "Creed Aventus / Mancera Cedrat Boise",
  },
  {
    id: 221,
    name: "Seoul Summer",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Notas verdes", "Manzana"], middle: ["Flor de azahar"], base: [] },
    description: "Fragancia fresca y acuática, ideal para el verano.",
    equivalence: "Invictus Aqua (Paco Rabanne)",
  },
  {
    id: 222,
    name: "Green Savage",
    category: "Hombre",
    scentFamily: "Fougere",
    notes: { top: ["Bergamota", "Lavanda"], middle: ["Madera de cedro"], base: [] },
    description: "Fragancia especiada y muy masculina con un carácter salvaje.",
    equivalence: "Dior Savage EDT",
  },
  {
    id: 223,
    name: "Night Pour Homme 3",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Cardamomo", "Lavanda"], middle: ["Ámbar"], base: [] },
    description: "Intensidad y elegancia nocturna con un corazón de lavanda.",
    equivalence: "L'Homme Parfum Intense (YSL) / Dior Homme Intense",
  },
  {
    id: 224,
    name: "Black Tag Intense",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Pimienta negra", "Bergamota"], middle: ["Vainilla"], base: [] },
    description: "Una fragancia dulce, especiada y profundamente nocturna.",
    equivalence: "Noir Extreme (Tom Ford)",
  },
  {
    id: 225,
    name: "Black Tag",
    category: "Hombre",
    scentFamily: "Cítrica",
    notes: { top: ["Pomelo", "Pimienta"], middle: ["Almizcle"], base: [] },
    description: "Frescura ahumada y marina para el hombre moderno.",
    equivalence: "Acqua di Gio Profumo (Giorgio Armani)",
  },
  {
    id: 226,
    name: "For Him Black Edition",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Nuez moscada", "Flor de Azahar"], middle: ["Sándalo"], base: [] },
    description: "Sofisticación oscura con toques especiados y florales.",
    equivalence: "Armani Code Profumo / La Nuit de L'Homme (YSL)",
  },
  {
    id: 227,
    name: "For Him",
    category: "Hombre",
    scentFamily: "Ambar / Oriental",
    notes: { top: ["Bergamota", "Cardamomo"], middle: ["Haba tonka"], base: [] },
    description: "Un aroma dulce y ambarado, un clásico de la masculinidad.",
    equivalence: "Jean Paul Gaultier Le Male",
  },
  {
    id: 228,
    name: "Energetically New York Elixir",
    category: "Hombre",
    scentFamily: "Amaderada",
    notes: { top: ["Cardamomo"], middle: ["Jazmín"], base: ["Sándalo"] },
    description: "Esta fragancia destaca por su perfil limpio, especiado y predominantemente amaderado.",
    equivalence: "SANTAL 33 LE LABO",
  },
  {
    id: 229,
    name: "Fashionably London Elixir",
    category: "Hombre",
    scentFamily: "Floral",
    notes: { top: ["Bergamota"], middle: ["Rosa", "Peonía"], base: ["Almizcle", "Aceite de Cedro"] },
    description: "Es un perfume lujoso donde la protagonista absoluta es la rosa, pero tratada de una forma moderna y sofisticada.",
    equivalence: "DELINA PARFUMS DE MARLY",
  }
];
